server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: utf-8

# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:s
    time-zone: GMT+8

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.codetime1234.springbootmybatis.user.entity
